server:
  port: 8082
spring.application.name: labs-service

spring:
  datasource:
    url: jdbc:oracle:thin:@x4jr6t1j9re665hr_high?TNS_ADMIN=/Users/gonzaloguerragaldames/labs-service/src/main/resources/Wallet_X4JR6T1J9RE665HR
    username: LAB_APP
    password: P4rM3d-Labs#2025!
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.OracleDialect

springdoc:
  swagger-ui:
    path: /swagger-ui
  group-configs:
    - group: labs
      paths-to-match: "/labs/**"
