server:
  port: 8083

spring:
  application:
    name: results-service

  datasource:
    url: jdbc:oracle:thin:@x4jr6t1j9re665hr_high?TNS_ADMIN=/Users/gonzaloguerragaldames/fullstack-labs/results-service/src/main/resources/Wallet_X4JR6T1J9RE665HR
    username: RESULTS_LABS
    password: P4rM3d-Labs#2025!
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.OracleDialect
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
